# Generated by Django 5.0.1 on 2024-01-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_collabgroup_recipes_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(to='main_app.collabgroup'),
        ),
    ]
