# Generated by Django 5.0.1 on 2024-01-17 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0003_alter_customuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='collab_groups',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='main_app.collabgroup'),
        ),
        migrations.AlterField(
            model_name='collabgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='instructions',
            field=models.TextField(),
        ),
    ]
