# Generated by Django 5.0.1 on 2024-01-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_customuser_collab_groups_alter_collabgroup_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.recipes'),
        ),
    ]
